const demoItems = [
  { title: "Engineering Mathematics Book", category: "Books", listingType: "rent", price: 15, description: "Reference book for semester preparation and exam practice.", condition: "Good", availability: "Available now", owner: "Arun", ownerEmail: "arun.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/F2EFE7/3368A0?text=Mathematics+Book", displayStyle: "portrait", status: "Available" },
  { title: "Data Structures and Algorithms", category: "Books", listingType: "sale", price: 280, description: "DSA textbook with solved examples for project and exam preparation.", condition: "Very Good", availability: "Available now", owner: "Meena", ownerEmail: "meena.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/C8DFDB/3368A0?text=DSA+Book", displayStyle: "portrait", status: "Available" },
  { title: "Scientific Calculator", category: "Electronics", listingType: "rent", price: 10, description: "Student calculator for mathematics and engineering examinations.", condition: "Good", availability: "Available now", owner: "Karthik", ownerEmail: "karthik.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/66A3BF/F2EFE7?text=Calculator", displayStyle: "landscape", status: "Available" },
  { title: "Wireless Headphones", category: "Electronics", listingType: "rent", price: 35, description: "Comfortable headphones for library study and online classes.", condition: "Excellent", availability: "Available now", owner: "Priya", ownerEmail: "priya.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/F2EFE7/3368A0?text=Headphones", displayStyle: "landscape", status: "Available" },
  { title: "Laptop Stand", category: "Electronics", listingType: "sale", price: 450, description: "Foldable stand suitable for hostel desks and study tables.", condition: "Excellent", availability: "Available now", owner: "Vishal", ownerEmail: "vishal.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/C8DFDB/3368A0?text=Laptop+Stand", displayStyle: "landscape", status: "Available" },
  { title: "Python Programming Notes", category: "Notes", listingType: "rent", price: 8, description: "Compact notes for Python programming and practical preparation.", condition: "Good", availability: "Available now", owner: "Divya", ownerEmail: "divya.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/66A3BF/F2EFE7?text=Python+Notes", displayStyle: "portrait", status: "Available" },
  { title: "DBMS Revision Notes", category: "Notes", listingType: "sale", price: 60, description: "Quick revision material covering SQL, normalization and transactions.", condition: "Very Good", availability: "Available now", owner: "Rahul", ownerEmail: "rahul.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/F2EFE7/3368A0?text=DBMS+Notes", displayStyle: "portrait", status: "Available" },
  { title: "Football", category: "Sports", listingType: "rent", price: 20, description: "Campus football for weekend games and practice sessions.", condition: "Good", availability: "Available now", owner: "Sanjay", ownerEmail: "sanjay.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/C8DFDB/3368A0?text=Football", displayStyle: "square", status: "Available" },
  { title: "Badminton Racket", category: "Sports", listingType: "rent", price: 25, description: "Lightweight racket for recreational campus games.", condition: "Excellent", availability: "Available now", owner: "Nisha", ownerEmail: "nisha.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/66A3BF/F2EFE7?text=Badminton+Racket", displayStyle: "portrait", status: "Available" },
  { title: "Study Backpack", category: "Others", listingType: "sale", price: 350, description: "Spacious backpack with laptop compartment and multiple pockets.", condition: "Excellent", availability: "Available now", owner: "Aditya", ownerEmail: "aditya.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/F2EFE7/3368A0?text=Study+Backpack", displayStyle: "portrait", status: "Available" },
  { title: "USB Mechanical Keyboard", category: "Electronics", listingType: "rent", price: 25, description: "Mechanical keyboard for coding and project work.", condition: "Excellent", availability: "Available now", owner: "Harish", ownerEmail: "harish.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/C8DFDB/3368A0?text=Keyboard", displayStyle: "landscape", status: "Available" },
  { title: "Study Desk Lamp", category: "Others", listingType: "sale", price: 220, description: "Compact study lamp for hostel rooms and late-night reading.", condition: "Good", availability: "Available now", owner: "Sneha", ownerEmail: "sneha.demo@vitstudent.ac.in", imageUrl: "https://placehold.co/900x600/66A3BF/F2EFE7?text=Desk+Lamp", displayStyle: "square", status: "Available" }
];

module.exports = demoItems;
