import React, { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./ListItem.css";
import "./ListItemEnhancements.css";

const API_URL = "http://localhost:5000";
const prohibitedPattern = /\b(drug|drugs|cocaine|heroin|meth|methamphetamine|marijuana|cannabis|weed|ganja|hashish|hash|opioid|fentanyl|lsd|mdma|ecstasy|ketamine|amphetamine|narcotic|steroid|steroids|prescription\s+medicine|controlled\s+substance)\b/i;

function ListItem() {
  const navigate = useNavigate();
  const fileInputRef = useRef(null), cameraInputRef = useRef(null);
  const [image, setImage] = useState(null), [imageFile, setImageFile] = useState(null), [dragging, setDragging] = useState(false);
  const [displayStyle, setDisplayStyle] = useState("square"), [listingType, setListingType] = useState("rent");
  const [message, setMessage] = useState(""), [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({ name: "", category: "", price: "", description: "", condition: "", availability: "" });

  const acceptImage=(file)=>{if(!file)return;if(!file.type.startsWith("image/"))return setMessage("Please select a valid image file.");if(file.size>5*1024*1024)return setMessage("Image size must be less than 5 MB.");if(image)URL.revokeObjectURL(image);setImage(URL.createObjectURL(file));setImageFile(file);setMessage("")};
  const handleFile=(e)=>acceptImage(e.target.files?.[0]);
  const handleDrop=(e)=>{e.preventDefault();setDragging(false);acceptImage(e.dataTransfer.files?.[0])};
  useEffect(()=>()=>{if(image)URL.revokeObjectURL(image)},[image]);
  const handleChange=(e)=>{const{name,value}=e.target;setFormData(p=>({...p,[name]:value}));setMessage("")};
  const handleSubmit=async(e)=>{e.preventDefault();setMessage("");if(!imageFile)return setMessage("Please add an item photo.");if(!formData.name.trim()||!formData.category||!formData.price||!formData.description.trim()||!formData.condition||!formData.availability)return setMessage("Please fill in all item details.");if(prohibitedPattern.test(`${formData.name} ${formData.category} ${formData.description}`))return setMessage("Drugs and controlled substances are strictly prohibited on Borrow Box.");let user=null;try{user=JSON.parse(localStorage.getItem("borrowBoxUser")||"null")}catch{}if(!user?.email)return navigate("/login");setLoading(true);try{const data=new FormData();data.append("image",imageFile);data.append("title",formData.name.trim());data.append("category",formData.category);data.append("listingType",listingType);data.append("price",formData.price);data.append("description",formData.description.trim());data.append("condition",formData.condition);data.append("availability",formData.availability);data.append("displayStyle",displayStyle);data.append("owner",user.nickname||"Student");data.append("ownerEmail",user.email);const r=await fetch(`${API_URL}/api/items`,{method:"POST",body:data});const d=await r.json();if(!r.ok)return setMessage(d.message||"Unable to list item.");setMessage("✓ Successfully listed your item on Borrow Box!");setTimeout(()=>navigate("/browse",{replace:true}),1000)}catch(err){console.error(err);setMessage("Cannot connect to Borrow Box server. Make sure backend is running.")}finally{setLoading(false)}};
  return <div className="list-page"><header className="list-header"><div className="list-brand" onClick={()=>navigate("/home")}><div className="list-logo">◇</div><div><strong>Borrow Box</strong><span>Campus sharing</span></div></div><button className="back-btn" onClick={()=>navigate("/browse")}>← Back</button></header><main className="list-container"><div className="list-title"><span>SELL / SHARE</span><h1>List an Item</h1><p>Choose whether your item is available to rent or sell.</p></div><form className="list-form" onSubmit={handleSubmit}>
    <section className="form-section"><div className="section-heading"><div><h2>Listing Type</h2><p className="section-desc">Select how another student can get your item.</p></div><span className="required-text">Required</span></div><div className="listing-type-options"><button type="button" className={`listing-type-card ${listingType==="rent"?"selected":""}`} onClick={()=>setListingType("rent")}><span className="listing-type-icon">↻</span><strong>Rent</strong><span>Student returns the item after the selected period.</span></button><button type="button" className={`listing-type-card ${listingType==="sale"?"selected":""}`} onClick={()=>setListingType("sale")}><span className="listing-type-icon">✓</span><strong>Sale</strong><span>One-time purchase. Approved order marks the item Sold.</span></button></div></section>
    <section className="form-section"><div className="section-heading"><div><h2>Item Photo</h2><p className="section-desc">Add a clear photo using one of the two options below.</p></div><span className="required-text">Required</span></div><div className="frame-section"><label>Image Display</label><div className="frame-options">{[["square","Square","1:1","General"],["portrait","Portrait","4:5","Books / Mobile"],["landscape","Landscape","16:10","Laptop / Monitor"]].map(([v,t,r,n])=><button key={v} type="button" className={`frame-option ${displayStyle===v?"selected":""}`} onClick={()=>setDisplayStyle(v)}><strong>{t}</strong><span>{r}</span><small>{n}</small></button>)}</div></div>
      <div className="photo-choice-grid"><button type="button" className={`photo-drop-zone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={handleDrop} onClick={()=>fileInputRef.current?.click()}><span className="photo-choice-icon">↑</span><strong>Upload / Drag & Drop</strong><span>Choose an image or drop it here</span><small>PNG, JPG, JPEG, WEBP · Max 5 MB</small></button><button type="button" className="photo-camera-zone" onClick={()=>cameraInputRef.current?.click()}><span className="photo-choice-icon">⌾</span><strong>Take Photo</strong><span>Use your device camera</span><small>Camera access will be requested</small></button></div>
      <input ref={fileInputRef} type="file" accept="image/png,image/jpeg,image/jpg,image/webp" onChange={handleFile} hidden/><input ref={cameraInputRef} type="file" accept="image/*" capture="environment" onChange={handleFile} hidden/>
      {image&&<div className={`image-upload-preview ${displayStyle}`}><img src={image} alt="Item preview"/><button type="button" onClick={()=>{URL.revokeObjectURL(image);setImage(null);setImageFile(null)}}>Remove photo</button></div>}
    </section>
    <section className="form-section"><div className="section-heading"><div><h2>Item Details</h2><p className="section-desc">Provide accurate information about your item.</p></div></div><div className="form-grid"><div className="input-group full"><label htmlFor="name">Item name</label><input id="name" name="name" placeholder="Eg. Scientific Calculator" value={formData.name} onChange={handleChange} required/></div><div className="input-group"><label htmlFor="category">Category</label><select id="category" name="category" value={formData.category} onChange={handleChange} required><option value="">Select category</option>{["Books","Electronics","Notes","Sports","Others"].map(x=><option key={x}>{x}</option>)}</select></div><div className="input-group"><label htmlFor="price">{listingType==="rent"?"Price per day":"Sale price"}</label><div className="price-input"><span>₹</span><input id="price" name="price" type="number" min="0" placeholder={listingType==="rent"?"50":"500"} value={formData.price} onChange={handleChange} required/></div></div><div className="input-group full"><label htmlFor="description">Description</label><textarea id="description" name="description" rows="5" placeholder="Describe your item, its condition and anything the buyer/borrower should know..." value={formData.description} onChange={handleChange} required/></div><div className="input-group"><label htmlFor="condition">Condition</label><select id="condition" name="condition" value={formData.condition} onChange={handleChange} required><option value="">Select condition</option>{["New","Like New","Good","Fair"].map(x=><option key={x}>{x}</option>)}</select></div><div className="input-group"><label htmlFor="availability">Availability</label><select id="availability" name="availability" value={formData.availability} onChange={handleChange} required><option value="">Select availability</option><option>Available now</option><option>Available from tomorrow</option></select></div></div></section>
    <div className="prohibited-notice"><strong>Strictly prohibited</strong><span>Drugs, controlled substances and illegal drug-related products cannot be sold, rented or listed on Borrow Box.</span></div>{message&&<div className={message.startsWith("✓")?"list-message success":"list-message error"}>{message}</div>}<div className="form-actions"><button type="button" className="cancel-btn" onClick={()=>navigate("/browse")} disabled={loading}>Cancel</button><button type="submit" className="submit-btn" disabled={loading}>{loading?"Listing Item...":`List ${listingType==="sale"?"for Sale":"for Rent"}`} {!loading&&<span>→</span>}</button></div>
  </form></main></div>;
}
export default ListItem;
