import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./MyItems.css";
import "./MyItemsEnhancements.css";
import "./MyItemsDeleteEnhancements.css";

const API_URL = "http://localhost:5000";
function MyItems(){const navigate=useNavigate();const[activeTab,setActiveTab]=useState("products"),[items,setItems]=useState([]),[requests,setRequests]=useState([]),[borrowed,setBorrowed]=useState([]),[loading,setLoading]=useState(true),[actionLoading,setActionLoading]=useState(""),[error,setError]=useState(""),[deleteTarget,setDeleteTarget]=useState(null);let storedUser=null;try{storedUser=JSON.parse(localStorage.getItem("borrowBoxUser")||"null")}catch{}const email=storedUser?.email||"";
const loadData=async()=>{if(!email)return navigate("/login",{replace:true});try{setLoading(true);setError("");const[a,b,c]=await Promise.all([fetch(`${API_URL}/api/items`),fetch(`${API_URL}/api/borrow-requests/owner/${encodeURIComponent(email)}`),fetch(`${API_URL}/api/borrow-requests/borrower/${encodeURIComponent(email)}`)]);const ad=await a.json(),bd=await b.json(),cd=await c.json();if(!a.ok)throw Error(ad.message||"Unable to load products.");if(!b.ok)throw Error(bd.message||"Unable to load requests.");if(!c.ok)throw Error(cd.message||"Unable to load borrowing.");setItems((ad.items||[]).filter(i=>String(i.ownerEmail||"").toLowerCase()===email.toLowerCase()));setRequests(bd.requests||[]);setBorrowed((cd.requests||[]).filter(r=>["Pending","Approved"].includes(r.status)))}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{loadData()},[]);
const processRequest=async(id,action)=>{try{setActionLoading(`${id}-${action}`);const r=await fetch(`${API_URL}/api/borrow-requests/${id}/${action}`,{method:"PUT"});const d=await r.json();if(!r.ok)throw Error(d.message);await loadData()}catch(e){setError(e.message)}finally{setActionLoading("")}};
const deleteItem=async()=>{if(!deleteTarget)return;try{setActionLoading(`delete-${deleteTarget._id}`);const r=await fetch(`${API_URL}/api/items/${deleteTarget._id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ownerEmail:email})});const d=await r.json();if(!r.ok)throw Error(d.message||"Unable to delete item.");setDeleteTarget(null);await loadData()}catch(e){setError(e.message)}finally{setActionLoading("")}};
const formatDate=d=>d?new Date(d).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";const imageUrl=i=>!i?.imageUrl?"":i.imageUrl.startsWith("http")?i.imageUrl:`${API_URL}${i.imageUrl}`;const mapUrl=r=>r.location?.latitude!=null&&r.location?.longitude!=null?`https://www.openstreetmap.org/?mlat=${r.location.latitude}&mlon=${r.location.longitude}#map=18/${r.location.latitude}/${r.location.longitude}`:"";if(loading)return <div className="myitems-page"><div className="myitems-loading">Loading My Products...</div></div>;
return <div className="myitems-page"><header className="myitems-header"><div className="myitems-brand" onClick={()=>navigate("/home")}><div className="myitems-logo">◇</div><div><strong>Borrow Box</strong><span>Campus sharing</span></div></div><button className="myitems-back" onClick={()=>navigate("/home")}>← Back</button></header><main className="myitems-container"><div className="myitems-heading"><span>MY ACTIVITY</span><h1>My Products</h1><p>Manage your listed products, incoming orders and active borrowing.</p></div>{error&&<div className="myitems-error">{error}</div>}<div className="myitems-tabs"><button className={activeTab==="products"?"active":""} onClick={()=>setActiveTab("products")}>My Products <span>{items.length}</span></button><button className={activeTab==="requests"?"active":""} onClick={()=>setActiveTab("requests")}>Requests <span>{requests.filter(r=>r.status==="Pending").length}</span></button><button className={activeTab==="borrowed"?"active":""} onClick={()=>setActiveTab("borrowed")}>My Borrowing <span>{borrowed.length}</span></button></div>
{activeTab==="products"&&<section className="myitems-list">{!items.length?<div className="myitems-empty"><strong>No products listed yet</strong><p>List something useful for students on your campus.</p></div>:items.map(item=><article className="myitem-card" key={item._id}><div className="myitem-image">{imageUrl(item)?<img src={imageUrl(item)} alt={item.title}/>:"◇"}</div><div className="myitem-content"><div className="myitem-main"><div className="myitem-meta"><span className="myitem-category">{item.category}</span><span className="listing-badge">{item.listingType==="sale"?"SALE":"RENT"}</span></div><h2>{item.title}</h2><p>{item.listingType==="sale"?`₹${item.price} • Permanent`:`₹${item.price} / day`}</p></div><span className={`myitem-status ${String(item.status||"Available").toLowerCase()}`}>● {item.status}</span></div><div className="myitem-card-actions"><button className="myitem-more" onClick={()=>navigate(`/item-details/${item._id}`)}>View →</button>{item.status!=="Borrowed"&&<button className="myitem-delete-btn" onClick={()=>setDeleteTarget(item)}>Delete</button>}</div></article>)}</section>}
{activeTab==="requests"&&<section className="request-list">{!requests.length?<div className="myitems-empty"><strong>No requests yet</strong><p>Orders for your products will appear here.</p></div>:requests.map(r=><article className="request-card" key={r._id}><div className="request-card-top"><div><span className="myitem-category">{r.requestType==="Purchase"?"SALE ORDER":"RENT REQUEST"}</span><h2>{r.itemTitle}</h2></div><span className={`request-status ${r.status.toLowerCase()}`}>{r.status}</span></div><div className="request-info"><div><span>BUYER</span><strong>{r.borrower||"—"}</strong><small>{r.borrowerEmail||"Email not provided"}</small>{r.borrowerPhone&&<small>☎ {r.borrowerPhone}</small>}</div><div><span>ORDER TYPE</span><strong>{r.requestType==="Purchase"?"Permanent purchase":"Rental"}</strong></div>{r.requestType!=="Purchase"&&<div><span>RENTAL DATES</span><strong>{formatDate(r.startDate)} → {formatDate(r.endDate)}</strong></div>}<div><span>PRICE</span><strong>{r.requestType==="Purchase"?`₹${r.itemPrice}`:`₹${r.itemPrice} / day`}</strong></div></div><div className="request-location"><strong>📍 Pickup / delivery</strong><span>{r.landmark||"Location not provided"}</span>{mapUrl(r)&&<a className="map-view-button" href={mapUrl(r)} target="_blank" rel="noreferrer">⌖ Tap to view map</a>}</div>{r.message&&<p className="request-message">“{r.message}”</p>}{r.status==="Pending"&&<div className="request-actions"><button className="request-reject" disabled={!!actionLoading} onClick={()=>processRequest(r._id,"reject")}>Reject</button><button className="request-approve" disabled={!!actionLoading} onClick={()=>processRequest(r._id,"approve")}>{actionLoading===`${r._id}-approve`?"Approving...":r.requestType==="Purchase"?"Approve Sale":"Approve Rent"}</button></div>}{r.status==="Approved"&&r.requestType==="Borrow"&&<div className="request-actions"><button className="request-approve" disabled={!!actionLoading} onClick={()=>processRequest(r._id,"return")}>Mark as Returned</button></div>}</article>)}</section>}
{activeTab==="borrowed"&&<section className="request-list">{!borrowed.length?<div className="myitems-empty"><strong>No active borrowing</strong><p>Items you request will appear here.</p></div>:borrowed.map(r=><article className="request-card" key={r._id}><div className="request-card-top"><div><span className="myitem-category">{r.requestType==="Purchase"?"PURCHASE":"BORROWED"}</span><h2>{r.itemTitle}</h2></div><span className={`request-status ${r.status.toLowerCase()}`}>{r.status}</span></div><div className="request-info"><div><span>OWNER</span><strong>{r.owner}</strong></div><div><span>PRICE</span><strong>₹{r.itemPrice}{r.requestType==="Borrow"?" / day":""}</strong></div>{r.requestType==="Borrow"&&<div><span>DATES</span><strong>{formatDate(r.startDate)} → {formatDate(r.endDate)}</strong></div>}</div><div className="request-location"><strong>Your pickup / delivery</strong><span>{r.landmark||"Location not provided"}</span></div></article>)}</section>}<div className="myitems-add"><div><strong>Have something useful?</strong><p>Share it with students on your campus.</p></div><button onClick={()=>navigate("/list-item")}>+ List an Item</button></div></main>{deleteTarget&&<div className="delete-confirm-overlay" role="dialog" aria-modal="true"><div className="delete-confirm-card"><h3>Delete this item?</h3><p><strong>{deleteTarget.title}</strong> will be permanently removed from your listings. This action cannot be undone.</p><div className="delete-confirm-actions"><button className="delete-cancel" onClick={()=>setDeleteTarget(null)}>Cancel</button><button className="delete-confirm" disabled={actionLoading===`delete-${deleteTarget._id}`} onClick={deleteItem}>{actionLoading===`delete-${deleteTarget._id}`?"Deleting...":"Delete Item"}</button></div></div></div>}</div>}
export default MyItems;
