import React,{useEffect,useState} from "react";
import {BrowserRouter,Routes,Route,Navigate,useLocation,useNavigate} from "react-router-dom";
import GetStarted from "./pages/GetStarted";import Login from "./pages/Login";import SignUp from "./pages/SignUp";import Home from "./pages/Home";import Browse from "./pages/Browse";import ListItem from "./pages/ListItem";import ItemDetails from "./pages/ItemDetails";import MyItems from "./pages/MyItems";import Profile from "./pages/Profile";import BorrowRequest from "./pages/BorrowRequest";import Chat from "./pages/Chat";import SellerHistory from "./pages/SellerHistory";import NotificationBell from "./components/NotificationBell";import "./AppGuard.css";import "./AppTheme.css";import GlobalNavbar from "./components/GlobalNavbar";
const protectedPaths=["/home","/browse","/list-item","/item-details","/my-items","/profile","/borrow-request","/chat","/seller-history"];
function isLoggedIn(){try{const u=JSON.parse(localStorage.getItem("borrowBoxUser")||"null");return Boolean(u?.email)}catch{return false}}
function Protected({children}){return isLoggedIn()?children:<Navigate to="/login" replace/>}
function NavigationHelper(){const location=useLocation(),navigate=useNavigate(),loggedIn=isLoggedIn(),isHome=location.pathname==="/home",isProtected=protectedPaths.some(path=>location.pathname===path||location.pathname.startsWith(`${path}/`));if(!loggedIn||isHome||!isProtected)return null;return <button className="global-home-back" onClick={()=>navigate("/home",{replace:true})} aria-label="Back to Home">← Home</button>}
function GlobalNotifications(){return isLoggedIn()?<div className="global-notification-position"><NotificationBell/></div>:null}
function ThemeToggle(){const[dark,setDark]=useState(()=>document.documentElement.classList.contains("dark"));useEffect(()=>{const apply=()=>{const saved=localStorage.getItem("color-theme");const isDark=saved==="dark"||(!saved&&window.matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.classList.toggle("dark",isDark);setDark(isDark)};apply();window.addEventListener("borrowbox-theme-change",apply);return()=>window.removeEventListener("borrowbox-theme-change",apply)},[]);const toggle=()=>{const next=!document.documentElement.classList.contains("dark");document.documentElement.classList.toggle("dark",next);localStorage.setItem("color-theme",next?"dark":"light");window.dispatchEvent(new Event("borrowbox-theme-change"));setDark(next)};return <button id="theme-toggle" type="button" className="theme-toggle-btn" onClick={toggle} aria-label={dark?"Switch to light theme":"Switch to dark theme"} title={dark?"Light mode":"Dark mode"}><span aria-hidden="true">{dark?"☀":"☾"}</span></button>}
function GlobalThemeToggle(){return <div className="global-theme-toggle"><ThemeToggle/></div>}
function App(){return <BrowserRouter><GlobalNotifications/><NavigationHelper/><GlobalThemeToggle/><GlobalNavbar/><Routes><Route path="/" element={<Navigate to="/get-started" replace/>}/><Route path="/get-started" element={<GetStarted/>}/><Route path="/login" element={isLoggedIn()?<Navigate to="/home" replace/>:<Login/>}/><Route path="/signup" element={isLoggedIn()?<Navigate to="/home" replace/>:<SignUp/>}/><Route path="/home" element={<Protected><Home/></Protected>}/><Route path="/browse" element={<Protected><Browse/></Protected>}/><Route path="/list-item" element={<Protected><ListItem/></Protected>}/><Route path="/item-details/:id" element={<Protected><ItemDetails/></Protected>}/><Route path="/my-items" element={<Protected><MyItems/></Protected>}/><Route path="/profile" element={<Protected><Profile/></Protected>}/><Route path="/borrow-request/:id" element={<Protected><BorrowRequest/></Protected>}/><Route path="/borrow-request" element={<Protected><BorrowRequest/></Protected>}/><Route path="/chat/:orderId" element={<Protected><Chat/></Protected>}/><Route path="/chat" element={<Protected><Chat/></Protected>}/><Route path="/seller-history" element={<Protected><SellerHistory/></Protected>}/><Route path="*" element={<Navigate to="/get-started" replace/>}/></Routes></BrowserRouter>}
export default App;
